# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  # Workflow files stored in the
  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
